# https://circleci.com/docs/2.0/sample-config/#sample-configuration-with-sequential-workflow
# https://circleci.com/blog/circleci-matrix-jobs
version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:lts
  linux:
    docker:
      - image: cimg/base:2020.01
  macos:
    macos:
      xcode: 12.5.1
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
      shell: bash.exe
    resource_class: windows.medium

orbs:
  node: circleci/node@5.0.2

jobs:
  audit:
    executor: node
    steps:
      - checkout
      - run:
          name: Audit NPM packages
          command: yarn audit --level critical
  build:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build library
          command: yarn build
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Run tests
          command: yarn test:coverage && yarn codecov

workflows:
  run-ci:
    jobs:
      - audit
      - build
      - test:
          matrix:
            parameters:
              os: [linux, macos, windows]
              node-version: ["16.14.2"]
