name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  audit:
    name: Audit NPM packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn audit --severity critical

  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn build

  test:
    name: Test (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['16.9']
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn test:coverage
      - run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
